# /docker-compose.yml
version: '3'
name: enelearn
networks:
  enelearn:
    driver: bridge
    name: enelearn

services:
  db:
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: Hello|11
      MYSQL_DATABASE: enelearnsys
      MYSQL_USER: user0
      MYSQL_PASSWORD: Hello|11
    image: mysql:8.3
    networks:
      - enelearn
    ports:
      - 63306:3306
    volumes:
      - ./db:/var/lib/mysql:rw
    # - mysql_data:/var/lib/mysql

  ws:
    build:
      context: .
      dockerfile_inline: |
        FROM php:8.3-apache
        RUN a2enmod rewrite
        RUN docker-php-ext-install mysqli
        COPY src/ /var/www/html/
    container_name: ws
    depends_on:
      - db
    environment:
      WS_PATH_BASE: /var/www/html/
      WSM_DBHELPER_SERVER: db
      WSM_DBHELPER_USERNAME: user0
      WSM_DBHELPER_PASSWORD: Hello|11
      WSM_DBHELPER_DATABASE: enelearnsys
    #image: php:8.3-apache
    networks:
      - enelearn
    ports:
      - 62280:80
    volumes:
      - ./src:/var/www/html:rw

# volumes:
#   mysql_data:

